from __future__ import annotations

STATUS_ID_APPLICATION_FILED = 1
STATUS_ID_NON_PROVISIONAL_APPLICATION = 2
STATUS_ID_PUBLICATION = 3
STATUS_ID_REQUEST_FOR_EXAMINATION = 4
STATUS_ID_FER_ISSUED = 5
STATUS_ID_FER_RESPONSE_SUBMITTED = 6
STATUS_ID_HEARING = 7
STATUS_ID_REFUSED = 8
STATUS_ID_GRANTED = 9
STATUS_ID_ABANDONED = 10

# Backward-compatible aliases
STATUS_ID_FIRST_EXAMINATION_REPORT = STATUS_ID_FER_RESPONSE_SUBMITTED
STATUS_ID_UNDER_HEARING = STATUS_ID_HEARING

STATUS_LABELS: dict[int, str] = {
    STATUS_ID_APPLICATION_FILED: "Application Filed",
    STATUS_ID_NON_PROVISIONAL_APPLICATION: "Non-Provisional application",
    STATUS_ID_PUBLICATION: "Publication",
    STATUS_ID_REQUEST_FOR_EXAMINATION: "Request for Examination",
    STATUS_ID_FER_ISSUED: "FER Issued",
    STATUS_ID_FER_RESPONSE_SUBMITTED: "FER Response submitted",
    STATUS_ID_HEARING: "Hearing",
    STATUS_ID_REFUSED: "Refused",
    STATUS_ID_GRANTED: "Granted",
    STATUS_ID_ABANDONED: "Abandoned",
}

OPTIONAL_STATUS_IDS = frozenset(
    {STATUS_ID_PUBLICATION, STATUS_ID_REQUEST_FOR_EXAMINATION, STATUS_ID_REFUSED}
)

TERMINAL_STATUS_IDS = frozenset(
    {STATUS_ID_REFUSED, STATUS_ID_GRANTED, STATUS_ID_ABANDONED}
)

ALL_STATUS_IDS = frozenset(STATUS_LABELS.keys())


def status_label(status_id: int) -> str:
    return STATUS_LABELS.get(status_id, f"Status {status_id}")
